name: Secret Demo

on:
  workflow_dispatch:

jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: displaying the secret content
        run: |
            echo "user name:${{secrets.MY_NAME}}"