name: Sequential Jobs Execution (needs)
on:
  workflow_dispatch:

jobs:
  bulid:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "building..."
            sleep 5
            echo "completed building..."
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "testing"
            sleep 5
            echo "completed testing"